apiVersion: apps/v1
kind: Deployment
metadata:
  name: kartkayae-rapidfort-assignment-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: kartikayae/apiproject:latest
          ports:
            - containerPort: 8080