apiVersion: v1
kind: Service
metadata:
  name: kartikayae-rapidfort-assignment-service
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080