name: Setup JDK and Gradle

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Grant permission
        run: chmod +x gradlew
          
      - name: Setup Gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload build JAR
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
